# place holder for the API Manifest
openapi: 3.0.1
info:
  title: Ramp up Plugin
  description: A plugin that allows new employees to ramp up faster and current employees to reskill faster.
  version: 'v0.1'
servers:
  - url: http://localhost:5003
paths:
  /skills/{role}:
    get:
      operationId: getSkills
      summary: Get the list of Skills
      parameters:
      - in: path
        name: username
        schema:
            type: string
        required: true
        description: List of Skills.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getTodosResponse'
    
   

components:
  schemas:
    getTodosResponse:
      type: object
      properties:
        todos:
          type: array
          items:
            type: string
          description: The list of todos.
